import Head from "next/head";
import IndexPage from "@pages/home-static-image/index";

export default function Home({ title }) {
  return (
    <>
      <Head>
        <title>Twelves eCommerce</title>
        <meta name="description" content="Generated by Kalles" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main>
        <IndexPage />
      </main>
    </>
  );
}